version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: little_lemmon
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./littlelemon:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
